### ISSUE TITLE
Toast sometimes doesn't work

### ISSUE THREAD

**Issue by pranky89** [versa-syahptr/winotify#11]
I am seeing an issue on some systems where toast is not shown to the user, this boils down to the powershell inability as manually trying also doesnt work so i wanted to check if you heard about it? Or know what to do or look for

**Comment by maxwill-max** [comment]
I think it might be due to previous notifications staying in the action center? is it possible to clear notifications off the action center from sending a new notification?

**Comment by versa-syahptr** [comment]
@maxwill-max was right, if you show notification that exact same with previous, it wont show.
