### ISSUE TITLE
non English language unreadeble

### ISSUE THREAD

**Issue by SofroN** [versa-syahptr/winotify#2]
When using a non-English language, the message is rendered unreadable
![img](https://user-images.githubusercontent.com/560988/116652700-68955780-a98e-11eb-909f-ca99ed19971e.png)

**Comment by versa-syahptr** [comment]
thanks for using winotify. For your issue, can you provide following information:
 - Windows 10 Version [e.g. 2004]
 - Windows Powershell Version [e.g. 5.1.19041.610]
 - Output from ```script``` property of the toast after ```build()``` the notification
```python
toast.build()
print(toast.script)
```
 - The language you are using and its encodings
 
Thank you.

**Comment by SofroN** [comment]
I use Russian lang.
```
Version          : 5.1.19041.610
CurrentCulture   : ru-RU
CurrentUICulture : ru-RU

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```
the problem is the default encoding used in windows. Windows uses `utf-16` python uses `utf-8`
For fix
```
        # Windows Notification encoding utf-16
        with NamedTemporaryFile('w', encoding='utf-16', suffix='.ps1', delete=False) as file:
            file.write(self.script)
```
