### ISSUE TITLE
Superb Lib but issues with Pyinstaller --noconsole option

### ISSUE THREAD

**Issue by pranky89** [versa-syahptr/winotify#4]
Trying to run the below code with pyinstaller and it's failing with --noconsole option, rest of the time it works fine. Do we know why?

`import os, sys
from winotify import Notification
from winotify import audio

def custom_toast_message(title, msg):
    toast = Notification(app_id="Notification powered by PP", title=title, msg=msg, 
    duration ='long')
    toast.add_actions(label="Close", link='https://google.com')        
    toast.set_audio(audio.Mail, loop=False)
    toast.build().show() 
	
custom_toast_message('hi there', 'champ is here')	
	`

**Comment by versa-syahptr** [comment]
What does it output when using `--noconsole` option?

**Comment by pranky89** [comment]
'Failed to run the script' ' [WinError 6] The handle is invalid'

Try to run a quick build with noconsole and you'll know what I am talking about.

**Comment by pranky89** [comment]
Do we have an update on this or We give up ?

**Comment by pranky89** [comment]
seems like your own main script doesn't work with --noconsole option, so no point in even try out my code. If you can fix your own code to work with pyinstaller, my code will work as well.

**Comment by versa-syahptr** [comment]
i have tried building `winotify.py` file with `--noconsole` option and everything works fine. Maybe the problem is from your pyinstaller?

**Comment by pranky89** [comment]
what was your build setup ? and also can you upload the file somewhere ?

**Comment by pranky89** [comment]
One more thing I noticed, if i am not using '--onefile' then everything works fine but when I am using --onefile, then it breaks the code somehow. Couldn't spot the difference in the file contents of both binaries as well..wat say?

**Comment by versa-syahptr** [comment]
So the problem is when you're using `--onefile` option?

**Comment by pranky89** [comment]
yes

**Comment by versa-syahptr** [comment]
Well, now the error with `--noconsole` option appears. Now i know the problem is from `subprocess.Popen`. I'm trying to fix it and if anybody wants to help I would really appreciate it.

**Comment by pranky89** [comment]
What call are we making using subprocess? I see dozens of so articles talking about issue with subprocess and how to fix it

**Comment by pranky89** [comment]
Check this out comment 1 and 2

https://stackoverflow.com/questions/24455337/pyinstaller-on-windows-with-noconsole-simply-wont-work

**Comment by versa-syahptr** [comment]
Thank you, I have fix it on the latest commit. Maybe you want to test it before I make a release?

**Comment by pranky89** [comment]
Sure, I’ll give it a shot in an hour.. what timezone you in?

**Comment by pranky89** [comment]
Tested, its Fixed ! Make a release !

**Comment by versa-syahptr** [comment]
I live in +7 UTC and it's already night here. I'll release it tomorrow
