### ISSUE TITLE
Notification not sitting in notification center

### ISSUE THREAD

**Issue by pranky89** [versa-syahptr/winotify#5]
Next one, when we receive a notification, its not staying in the notification center, just vanishes from the notification center after displaying. We need this to be fixed as well.

**Comment by versa-syahptr** [comment]
Try this:
[https://www.guidingtech.com/fixes-for-notifications-banners-not-showing-windows-10/](https://www.guidingtech.com/fixes-for-notifications-banners-not-showing-windows-10/)

**Comment by pranky89** [comment]
I don’t think that’s the issue. Go lang build is working and staying in Notification Center but your build is not... on same machine

**Comment by versa-syahptr** [comment]
What's your windows version & build number, and also your powershell version?

I found an issue in Go-toast repo that maybe related to this:
https://github.com/go-toast/toast/issues/9

**Comment by pranky89** [comment]
Nah i have seen that. In your case.. notifications are showing up but not sticking to nc. They are displayed and then vanished. We need them to sit in nc. Windows 10 and 2016 both have this issue

**Comment by versa-syahptr** [comment]
Try filling the app id with a real one, for example: `"{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe"`

**Comment by versa-syahptr** [comment]
is that fix the problem? because in my machine (windows v. 2004) it works fine. the notification shows and stays in nc.
here's the screenshot
![Screenshot (214)](https://user-images.githubusercontent.com/55734080/120138297-6bd76980-c200-11eb-9707-faf348bb68ae.png)

**Comment by pranky89** [comment]
we can close this one, its working on another system, seems something wrong wtih those two systems.
