### ISSUE TITLE
(Enhancement) Need to add --activation-arg 

### ISSUE THREAD

**Issue by pranky89** [versa-syahptr/winotify#6]
We need to be able to click on the toast and open a link or do something.
Something like this lib : https://github.com/go-toast/toast

Thanks..

**Comment by versa-syahptr** [comment]
Go-toast is my inspiration to make the same thing using python. That feature is already exists since the first release. `--activation-arg` is equivalent to `--open-url` in winotify. Go give it a try and i'll close this thread.
