### ISSUE TITLE
Hides the main Command Prompt/PowerShell Window

### ISSUE THREAD

**Issue by binaryhabitat** [versa-syahptr/winotify#8]
**To Reproduce**
Take this example program
```python
input("Press enter to start")
from winotify import Notification
t = Notification(app_id="TEST",
                 title="TEST",
                 msg="TEST")
t.build().show()
input("Press enter to stop")
```

In Command Prompt/PowerShell, you will see the first input, after pressing enter and continuing the toast notification will appear but the cmd/ps window will disappear (it is still running and will be visible in Task Manager).

In PyCharm, the expected behavior occurs and "_Press enter to stop is shown_".

**Expected behavior**
Window does not disappear.

**Comment by binaryhabitat** [comment]
This is fixed by removing
```python
 "-WindowStyle", "Hidden",
 ```
 Is it required? Assume this actually a PowerShell bug effecting the main Window..

**Comment by versa-syahptr** [comment]
You were right, this is a PS bug, I'm gonna remove that line in the next update. Thank you
